### ISSUE TITLE
lru_cache Expected maxsize to be an integer or None

### ISSUE THREAD

**Issue by pkico** [yandex-research/RuLeanALBERT#1]
Пытался опробовать модель в colab (Python 3.9.14), но при попытке импортов, например 
`from src.models.albert import LeanAlbertForPreTraining`
выдает 
`[/content/RuLeanALBERT/src/modules/pixelfly.py](https://localhost:8080/#) in <module>
     17     n_factors: Optional[int] = None,
     18     stretch: bool = False,
---> 19 ) -> Tuple[torch.IntTensor, torch.IntTensor]:
     20     """
     21     Get a matrix [num_output_blocks, num_active_input_blocks] with int32 indices for additive butterfly.

[/usr/lib/python3.7/functools.py](https://localhost:8080/#) in lru_cache(maxsize, typed)
    488             maxsize = 0
    489     elif maxsize is not None:
--> 490         raise TypeError('Expected maxsize to be an integer or None')
    491 
    492     def decorating_function(user_function):

TypeError: Expected maxsize to be an integer or None`

**Comment by antonmisa** [comment]
В файле modules/pixelfly.py нотация @functools.lru_cache для python 3.8+, надо @functools.lru_cache()

**Comment by mryab** [comment]
Пофиксили в #2, теперь должно работать в более ранних версиях (хотя формально этот фрагмент кода вообще не нужен для модели, кажется). Спасибо за указание на проблему!
