### ISSUE TITLE
What is the correct way to tune the model for a multi-class classification task?

### ISSUE THREAD

**Issue by valeriylo** [yandex-research/RuLeanALBERT#3]
I recently learned about your impressive project and wanted to try it in a Russian text classification project of mine.
Could you please guide me to the correct fine-tuning steps? 

I'm a bit confused about the correct way to use your model: I've found several references in your repository ([albert.py](https://github.com/yandex-research/RuLeanALBERT/blob/0f08d1b67759960e36128c078c4b6d8103cc4759/src/models/albert.py#L393), [finetune_mlm.py](https://github.com/yandex-research/RuLeanALBERT/blob/0f08d1b67759960e36128c078c4b6d8103cc4759/finetune_mlm.py#L118), [also finetune_mlm.py](https://github.com/yandex-research/RuLeanALBERT/blob/0f08d1b67759960e36128c078c4b6d8103cc4759/finetune_mlm.py#L135)) and I'm aware of bert-like model fine-tuning practices.

Should I pass the desired `task` name in the config file and then define the model as `AutoModelForSequenceClassification.from_pretrained(...)`?

thanks

**Comment by mryab** [comment]
Hi @valeriylo, sorry for the delayed reply!

The correct way to use the model is as follows:
1. Create the config as in [finetune_mlm.py:L111-L113](https://github.com/yandex-research/RuLeanALBERT/blob/main/finetune_mlm.py#L111-L113), setting `num_labels` to the number of your classes.
2. Then, load the model using [L118-122](https://github.com/yandex-research/RuLeanALBERT/blob/main/finetune_mlm.py#L118-L122) from the same file. Please note that `AutoModelForSequenceClassification` in our code is used for the RuRoBERTa baseline and will not work for RuLeanALBERT.
3. That's it! You can proceed as usual with creating `TrainingArguments`, `Trainer` and finetuning the model.

If you run into any issues when running this on your task, I'm happy to help with them
